---
name: WWW-WhitePages
version: 2008.0813
author:
  - 'Eric R. Meyers <Eric.R.Meyers@gmail.com>'
abstract: Interface to www.whitepages.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTTP::Cookies: 0
  LWP::UserAgent: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
recommends:
  Test::Memory::Cycle: 0
  Test::Pod: 0
  Test::Taint: 0
  Test::Warn: 0
provides:
  WWW::WhitePages:
    file: lib/WWW/WhitePages.pm
    version: 2008.0813
  WWW::WhitePages::ML::API:
    file: lib/WWW/WhitePages/ML/API.pm
    version: 2008.0813
  WWW::WhitePages::XML:
    file: lib/WWW/WhitePages/XML.pm
    version: 2008.0813
  WWW::WhitePages::XML::API:
    file: lib/WWW/WhitePages/XML/API.pm
    version: 2008.0813
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
